"
I'm using to testing import feature of the BISettingPreviewer
"
Class {
	#name : #BIUseForTestWithMethod,
	#superclass : #Object,
	#instVars : [
		'biChooseMethod'
	],
	#category : #'MigratePrettyPrinterUI-Tests'
}

{ #category : #'as yet unclassified' }
BIUseForTestWithMethod class >> gandalf [
]

{ #category : #'as yet unclassified' }
BIUseForTestWithMethod >> methodA [
]

{ #category : #'as yet unclassified' }
BIUseForTestWithMethod >> methodB [
]
