"
I'm used to test import feature of the BISettingPreviewer.
"
Class {
	#name : #BIUseForTestWithMethod,
	#superclass : #Object,
	#instVars : [
		'biChooseMethod'
	],
	#category : #'EnlumineurUI-Tests'
}

{ #category : #'as yet unclassified' }
BIUseForTestWithMethod class >> gandalf [
]

{ #category : #operations }
BIUseForTestWithMethod >> methodA [
]

{ #category : #operations }
BIUseForTestWithMethod >> methodB [
]
